### ISSUE TITLE
CRITICAL : Feature vulnerable to spamming attack - please fix ASAP

### ISSUE THREAD

**Issue by arroway** [papey/o2m#17]
Dear sir, 
it's with deepest regrets that I have to inform you that the new feature implemented with PR #16 sadly introduces a misbehavior prone to abusive behaviors from the part of Discord users, especially the kind of l$ft-w$ng metalheads that tend to populate some server I believe you're acquainted with.

Indeed, multiple users would be able to set the "link" emoji used to display the music links information, which at the moment results in printing the bot information as many times in the channel - a.k.a spamming.
To prevent this, I suggest the links information are printed once, regardless of the number of emojis which are set.

Regards

**Comment by Clm-Roig** [comment]
+1 plz fix asap, it broke everything in production.

**Comment by papey** [comment]
![image](https://github.com/user-attachments/assets/8321cbb9-5cc9-406d-9e9d-cf9db1570374)

**Comment by papey** [comment]
https://github.com/papey/o2m/pull/18 :saluting_face:
